### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid_fulltext#42]
@tomasc any interest in helping out? If yes, wha's your rubygems email?

**Comment by tomasc** [comment]
@dblock sure – tomas.celizna@gmail.com

**Comment by dblock** [comment]
Invited https://github.com/mongoid/mongoid_fulltext/invitations and added to RubyGems.

Release at will. We need a RELEASING doc ala https://github.com/mongoid/mongoid-compatibility/blob/master/RELEASING.md too, if you could maybe steal that one and follow for here?

**Comment by tomasc** [comment]
ok, thanks.

**Comment by tomasc** [comment]
@dblock I have released 0.8.2
