### ISSUE TITLE
Cursor timing out

### ISSUE THREAD

**Issue by roykolak** [mongoid/mongoid_fulltext#44]
I'm trying to generate an ngram index for a large number of short phrases, around `3,000,000`.

I'm getting the following error a few minutes after kicking off `Model.update_ngram_index`

```shell
 Mongo::Error::OperationFailure (cursor id 331936703090 not found (43) ...`
```

Is there a config option I can pass to disable cursor timeouts? Any other recommendations?

**Comment by dblock** [comment]
Is it coming from [here](https://github.com/mongoid/mongoid_fulltext/blob/3d212b0eaec2b93b54d9514603bc24b3b2594104/lib/mongoid/full_text_search.rb#L293)?

I think `all.no_timeout.each(&:upgrade_ngram_index)` should do it. Give it a try?

We should probably just make it default. Consider a PR?

**Comment by roykolak** [comment]
Ah yep! That was it.

**Comment by dblock** [comment]
Will you make a PR to expose `options` in that method so the caller can pass `no_timeout` maybe?

**Comment by dblock** [comment]
Closed via https://github.com/mongoid/mongoid_fulltext/pull/45
